In [2]:
import numpy as np
# arange(): Create range of numbers like Python's range()
arr1 = np.arange(20, 30, 3)
print("Array using arange:", arr1)


Array using arange: [20 23 26 29]


In [4]:
# linspace(): Create evenly spaced values between two limits
arr2 = np.linspace(0, 2, 6)
print("Array using linspace:", arr2)

Array using linspace: [0.  0.4 0.8 1.2 1.6 2. ]


In [5]:
# reshape(): Change shape without changing data
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)

# flatten(): Convert multi-dimensional array to 1D
print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [6]:
data = np.array([[5, 8, 9], [2, 4, 6]])

print("Original Data:\n", data)

Original Data:
 [[5 8 9]
 [2 4 6]]


In [9]:
print("Sum of all elements:", np.sum(data))             # Total sum
print("Column-wise sum:", np.sum(data, axis=0))         # Sum along columns
print("Row-wise mean:", np.mean(data, axis=1))          # Average of each row
print("Max value:", np.max(data))                       # Maximum value


Sum of all elements: 34
Column-wise sum: [ 7 12 15]
Row-wise mean: [7.33333333 4.        ]
Max value: 9


In [10]:
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))                       # Minimum value
print("Standard Deviation:", np.std(data))              # Spread of values

Index of max value (flattened): 2
Min value: 2
Standard Deviation: 2.3570226039551585


In [11]:
a = np.array([4,5,6,7])
print("Original Array:", a)

Original Array: [4 5 6 7]


In [13]:
# Sort array values
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)

# Find indices where condition is True (value > 4)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])

Sorted Array: [4 5 6 7]
Indices where value > 4: (array([1, 2, 3]),)
Values > 4: [5 6 7]


In [12]:
# Broadcasting allows NumPy to perform operations between arrays of different shapes
A = np.array([[2, 9], [7, 5]])
B = np.array([50, 20])

print("Matrix A:\n", A)
print("Vector B:", B)


Matrix A:
 [[2 9]
 [7 5]]
Vector B: [50 20]


In [14]:
# B is broadcasted to each row of A
C = A + B
print("Broadcasted Addition Result:\n", C)

Broadcasted Addition Result:
 [[52 29]
 [57 25]]


In [15]:
nums = np.array([7,6,8, 4, 5])

# Create boolean mask for condition nums > 3
mask = nums > 3
print("Mask (nums > 3):", mask)

Mask (nums > 3): [ True  True  True  True  True]


In [16]:
# Use mask to filter values
filtered = nums[mask]
print("Filtered values:", filtered)

# np.where: apply conditional logic
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)


Filtered values: [7 6 8 4 5]
Even or Odd: ['Odd' 'Even' 'Even' 'Even' 'Odd']


In [17]:
arr_orig = np.array([10, 20, 30])

# Creating a view (shares memory)
arr_view = arr_orig[:]
arr_view[0] = 99  # This change affects original
print("Original After View Change:", arr_orig)


Original After View Change: [99 20 30]


In [19]:
# Creating a copy (independent)
arr_copy = arr_orig.copy()
arr_copy[0] = 45 # This does NOT affect original
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)

Original After Copy Change: [99 20 30]
Copy: [45 20 30]


In [20]:
x = np.array([7, 8, 9])
y = np.array([4, 1, 6])

# Vertical stack (as rows)
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)


Vertical Stack:
 [[7 8 9]
 [4 1 6]]


In [21]:
# Horizontal stack (as columns)
h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)

# Split an array into 3 sub-arrays
z = np.arange(10)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)

Horizontal Stack:
 [7 8 9 4 1 6]
Split into 3 parts: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [22]:

# Random integers from 0 to 100 in 3x3 matrix
rand_ints = np.random.randint(0, 100, size=(3, 3))
print("Random Integers:\n", rand_ints)

# Random values from standard normal distribution (mean=0, std=1)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)


Random Integers:
 [[19 38 45]
 [73 81 55]
 [57 77 56]]
Random Normal Distribution:
 [[ 1.93116323  1.22912603 -0.37074005  1.68815922]
 [ 0.53960035  1.36148938  0.19184341  0.61152399]]


In [23]:
# Random sampling from a custom list
choices = np.random.choice([1, 3, 5, 7], size=5)
print("Random Choices:", choices)

# Setting a seed ensures reproducible random results
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())

Random Choices: [5 7 1 3 1]
Seeded Random Number: 0.3745401188473625


In [24]:
# Create a sample 1D array
arr = np.array([12, 24, 36, 48, 50, 62])
print("Original 1D Array:", arr)

# Access single elements by index
print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])

Original 1D Array: [12 24 36 48 50 62]
Element at index 0: 12
Element at last index: 62


In [25]:
# Slice elements [start:stop] (stop is exclusive)
print("Slice from index 1 to 4:", arr[1:4])

# Slice with step
print("Every second element:", arr[::2])

# Reverse array
print("Reversed array:", arr[::-1])


Slice from index 1 to 4: [24 36 48]
Every second element: [12 36 50]
Reversed array: [62 50 48 36 24 12]


In [26]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)

# Access element at row 1, column 2
print("Element at (1,2):", matrix[1, 2])  # 6

# Get entire first row
print("First row:", matrix[0, :])  # [1, 2, 3]

# Get entire second column
print("Second column:", matrix[:, 1])  # [2, 5, 8]

# Slice sub-matrix (top-left 2x2 block)
print("Top-left 2x2 block:\n", matrix[:2, :2])  # [[1,2],[4,5]]

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
First row: [1 2 3]
Second column: [2 5 8]
Top-left 2x2 block:
 [[1 2]
 [4 5]]


In [27]:
arr = np.array([25, 17, 18, 25, 27, 39])

# Create a boolean mask for values > 25
mask = arr > 25
print("Boolean Mask:", mask)

# Use mask to filter elements
print("Values greater than 25:", arr[mask])

# Combine conditions
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])


Boolean Mask: [False False False False  True  True]
Values greater than 25: [27 39]
Even numbers > 10: [18]
